-- Per-site Redis object cache support
ALTER TABLE sites ADD COLUMN IF NOT EXISTS redis_cache BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS redis_db INTEGER NOT NULL DEFAULT 0;
